name: Project_2

services:
  proxy-server:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-server
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
